FROM ghcr.io/herlesupreeth/docker_kamailio:master

# Kamailio 6.2.x con módulos IMS (OpenIMSCore line) y las rutas SQL que esperan
# los init scripts del monorepo docker_open5gs:
#   /usr/local/src/kamailio/misc/examples/ims/icscf/icscf.sql
#   /usr/local/src/kamailio/utils/kamctl/mysql/*.sql
# Incluye cliente mysql y bash.